name: CI Workflow Scheme Gambit

on: [push, pull_request]

jobs:
  gambit_build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Install Gambit
      run: |
        sudo apt-get update
        sudo apt-get -y install gambc

    - name: Test
      run: gsi ./test/assert-test.scm

    - name: Test the example
      run: gsi ./sample/sample-unit-test.scm

  gambit_build_windows:
    runs-on: windows-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Install Gambit
      run: choco install gambit

    - name: Test
      run: gsi.exe test\assert-test.scm

    - name: Test the example
      run: gsi.exe sample\sample-unit-test.scm

    - name: Test the prime factors
      run: gsi.exe sample\prime-factors-test.scm
